### ISSUE TITLE
Hope for exporting to PDF

### ISSUE THREAD

**Issue by kerryChen95** [shuowu/yi-note#25]
Hope for exporting to PDF, so we can save into Evernote etc., and search from one entry.

**Comment by shuowu** [comment]
@kerryChen95 Exporting to PDF (also support Chinese character) is available since v1.1.0, please check if you have latest version installed, or you can upgrade it manually from chrome://extension page. 

Also directly exporting to Evernote will be available in next release. Please stay tuned :)

HowTO:
after you taking notes from YiNote panel, there will be a preview icon show up align with the bookmark icon. The generate pdf button is in the preview modal.
