### ISSUE TITLE
PDF time 

### ISSUE THREAD

**Issue by GlennHodnett** [shuowu/yi-note#33]
Hi 
Thanks for fixing the issues so quickly with the update, can the altered times in the timeline be reflected in the exported PDF file. i.e I enter a event at 30 secs into the video and in YiNote when i click on the event it plays 5/10/15 secs before whatever i've set it to in the settings which is perfect but the exported PDF will play from 30secs and not play from the preset time.
I work with football coaches and they analyse games, so they want to see/show build up play with the players, the exported PDF can be emailed out for players to review so they can just click on the link and it shows the build up play before the event. 

Could a feature to add basic drawing tools be added maybe? At the moment I use Epic Pen to draw on the screen
Ability to import XML files that already has a timeline that would sync with an uploaded video and show in the you tube comments? i've attached a picture of the XML data
![demo](https://user-images.githubusercontent.com/65905192/83319837-bd3dc900-a239-11ea-9c3c-c09410debb54.png)

Ability to make custom preset event buttons i.e Goal, Offside, Corner, Yellow card etc

Many thanks

**Comment by shuowu** [comment]
@GlennHodnett 
Per applying preset to generate links, like links in pdf, Evernote, google docs, etc, I will consider adding another setting to handle it.

Per adding annotation on top of the video, it's a great suggestion, but I am not planning to add it to YiNote before proper design. Since YiNote can send your notes to other note taking platforms, like Evernote, Oneonte, Googledocs, with screenshots included. You probably can pick a platform and send your notes there. Then you can use the well-designed annotation tool from there to add annotation. As all supported note taking platforms support sharing functionality very well, you probably can work with your team from there.

**Comment by shuowu** [comment]
#34 #35 has been created. I hope these two features can help. @GlennHodnett

**Comment by shuowu** [comment]
@GlennHodnett options have been added in the latest version v1.4.0. Also, annotate screenshot (not video) is also supported in v1.4.0. Please update the extension and verify how it works, thanks.

Close this issue.

**Comment by GlennHodnett** [comment]
Thank you love it!!! 😊  Sent from Mail for Windows 10 From: Shuo WuSent: 23 June 2020 15:01To: shuowu/yi-noteCc: GlennHodnett; MentionSubject: Re: [shuowu/yi-note] PDF time (#33) @GlennHodnett options have been added in the latest version v1.4.0. Also, annotate screenshot (not video) is also supported in v1.4.0. Please update the extension and verify how it works, thanks.Close this issue.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe. 

	
        
		Virus-free. www.avast.com
