### ISSUE TITLE
Text overscanning, losing notes

### ISSUE THREAD

**Issue by enlargedhousecats** [shuowu/yi-note#45]
![0H7atJ6rnT](https://user-images.githubusercontent.com/51523905/85234289-263fd900-b3c1-11ea-9072-fdfcaa2ebf76.gif)

I have encountered a pretty crucial issue with the interface of YI note.  version 1.3.0 from chrome web store.

text within the notes does not wrap to accommodate the size of Yi-note interface. There is no control to navigate from one end of the interface to the other, or to expand the size of the sidebar.

The functions on the right side of the interface are then hidden from view or control unless tabbed over. notes become unreadable

To repeat the process all I had to do was write a note that was longer than the interface of YiNote
![YhbBdXhxmV](https://user-images.githubusercontent.com/51523905/85234493-9c910b00-b3c2-11ea-8d6f-fa4a647d3df1.gif)
![fQyOfethMm](https://user-images.githubusercontent.com/51523905/85234533-ccd8a980-b3c2-11ea-9d66-953eb8b6de79.gif)

**Comment by shuowu** [comment]
@enlargedhousecats Thanks for the detailed reporting. I am currently working on markdown support on editing and view notes, it will be released soon in newer version 1.4.0. This issue will also be fixed in the next version. Please stay tuned. 

Below is the preview of the new markdown editor (plain text notes will still be supported with no issue)
![Screen Shot 2020-06-22 at 12 15 10 PM](https://user-images.githubusercontent.com/4027992/85310485-0ae8d280-b482-11ea-8dbb-a8f470ba8c9c.png)

**Comment by enlargedhousecats** [comment]
Thank you for the quick reply, This is a huge improvement! I am excited for version 1.4.0

**Comment by shuowu** [comment]
v1.4.0 has been published in chrome web store, please update the extension and verify if the issue has been fixed.
